set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $CART_DB_USER WITH PASSWORD '$CART_DB_PASSWORD';
    CREATE DATABASE $CART_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $CART_DB_NAME TO $CART_DB_USER;
    ALTER DATABASE $CART_DB_NAME OWNER TO $CART_DB_USER;
EOSQL