spring:
  application:
    name: @project.artifactId@

  cloud:
    gateway:
      routes:
        - id: catalog
          uri: http://localhost:8081/
          predicates:
            - Path=/catalog/**
        - id: auth
          uri: http://localhost:8083/
          predicates:
            - Path=/auth/**

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost