server:
  port:
    8888

spring:
  application:
    name: config-service

  profiles:
    active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/surmalune/bookstore-config-repo.git
          clone-on-start: true
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:s3cr3t@localhost:8761/eureka
  instance:
    hostname: localhost